name: Ruijie BE68U Build
on:
  workflow_dispatch:
  push:
    branches: ["mt798x-mt799x-mtwifi_be72pro_be68u"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # 清理磁盘空间
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison openssl libssl-dev device-tree-compiler libz-dev libelf-dev python3 python3-pip unzip curl

      - name: Config BE68U
        run: |
          make defconfig
          # 目标机型
          echo "CONFIG_TARGET_mediatek_mt798x_DEVICE_ruijie_be68u=y" >> .config
          # 基础LuCI & 中文
          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-zh-cn=y" >> .config
          # 【禁用bug包】
          echo "# CONFIG_PACKAGE_autosamba is not set" >> .config
          echo "# CONFIG_PACKAGE_autocore is not set" >> .config
          echo "# CONFIG_PACKAGE_autosmb is not set" >> .config
          echo "# CONFIG_PACKAGE_default-settings is not set" >> .config
          echo "# CONFIG_PACKAGE_emortal-automount is not set" >> .config
          # 【禁用Docker】
          echo "# CONFIG_PACKAGE_docker is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-docker is not set" >> .config

      - name: Compile firmware
        run: make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: BE68U-Firmware
          path: bin/targets/**


